## Script to combine and search ENA tables for marine metagenome samples
## For this search 3 tables were exported from ENA advanced search, using Thermoplasmata, ecological metagenomes and unclassified metagenomes, the Thermoplasmatota table downlaoded in a second step was used as a whole table 

library(dplyr)

setwd("C:/Users/admin/OneDrive/PhD/Thermoplasmata/Data_mining")

ThermoplasmataMG <- read.table("genome_assembly_Thermoplasmata_results_assembly_tsv.txt", sep="\t", header=T, fill = TRUE, check.names = FALSE)
ecoMG <- read.table("genome_assembly_eco_metaG_results_assembly_tsv.txt", sep="\t", header=T, fill = TRUE,check.names = FALSE)
unclassifiedMG <- read.table("genome_assembly_unclassified_sequences_results_assembly_tsv.txt", sep="\t", header=T,fill = TRUE, check.names = FALSE)


# combine by row
merged_assemblies <- rbind(ThermoplasmataMG,ecoMG,unclassifiedMG)

# get a list of all unique values
listMGs <- c(unique(merged_assemblies$scientific_name))

# manually check unique values for needed MAGs
# if not clear what scientific_name is referring to, also check further information of assembly.

sink('listMGs.txt')
print(listMGs)
sink()

# Subsetting assemblies using only scientific names of interest
subset_assemblies <- subset(merged_assemblies, merged_assemblies$scientific_name %in% c("ThermoplasmavolcaniumGSS1",
                                                                                   "ThermoplasmaacidophilumDSM1728",
                                                                                   "CandidatusMethanomethylophilusalvusMx1201",
                                                                                   "MethanomassiliicoccusluminyensisB10",
                                                                                   "ThermoplasmatalesarchaeonSCGCAB-539-N05",
                                                                                   "ThermoplasmatalesarchaeonSCGCAB-540-F20",
                                                                                   "ThermoplasmatalesarchaeonBRNA1",
                                                                                   "ThermoplasmatalesarchaeonSCGCAB-539-C06",
                                                                                   "MarineGroupIIIeuryarchaeoteSCGCAAA007-O11",
                                                                                   "MarineGroupIIIeuryarchaeoteSCGCAAA288-E19",
                                                                                   "CandidatusMethanomassiliicoccusintestinalisIssoire-Mx1",
                                                                                   "ThermoplasmatalesarchaeonA-plasma",
                                                                                   "ThermoplasmatalesarchaeonE-plasma",
                                                                                   "CandidatusMethanoplasmatermitum",
                                                                                   "ThermogymnomonasacidicolaJCM13583",
                                                                                   "MethanomassiliicoccalesarchaeonRumEnM2",
                                                                                   "MethanomassiliicoccalesarchaeonRumEnM1",
                                                                                   "CandidatusMethanomethylophilussp.1R26",
                                                                                   "Thermoplasmatalesarchaeon49_6",
                                                                                   "methanogenicarchaeonISO4-H5",
                                                                                   "ThermoplasmatalesarchaeonSG8-52-1",
                                                                                   "ThermoplasmatalesarchaeonSG8-52-2",
                                                                                   "ThermoplasmatalesarchaeonSG8-52-4",
                                                                                   "ThermoplasmatalesarchaeonSG8-52-3",
                                                                                   "ThermoplasmatalesarchaeonSM1-50",
                                                                                   "ThermoplasmatalesarchaeonI-plasma",
                                                                                   "ThermoplasmatalesarchaeonGpl",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Epi1",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Epi3",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Epi4",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Epi6",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Bathy1",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Bathy2",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Epi5",
                                                                                   "MarineGroupIIIeuryarchaeoteCG-Epi2",
                                                                                   "ThermoplasmatalesarchaeonJdFR-43",
                                                                                   "MethanomassiliicoccalesarchaeonPtaB.Bin215",
                                                                                   "MethanomassiliicoccalesarchaeonPtaB.Bin134",
                                                                                   "MethanomassiliicoccalesarchaeonPtaU1.Bin030",
                                                                                   "MethanomassiliicoccalesarchaeonPtaU1.Bin124",
                                                                                   "ThermoplasmatalesarchaeonARMAN",
                                                                                   "ThermoplasmatalesarchaeonB_DKE",
                                                                                   "Thermoplasmatalesarchaeonex4484_6",
                                                                                   "Thermoplasmatalesarchaeonex4484_30",
                                                                                   "Thermoplasmatalesarchaeonex4484_36",
                                                                                   "Thermoplasmatalesarchaeonex4572_165",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA409",
                                                                                   "Methanomassiliicoccussp.UBA238",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA482",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA396",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA387",
                                                                                   "ThermoplasmataarchaeonUBA184",
                                                                                   "EuryarchaeotaarchaeonUBA139",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA593",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA394",
                                                                                   "Methanomassiliicoccussp.UBA292",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA378",
                                                                                   "ThermoplasmatalesarchaeonUBA511",
                                                                                   "EuryarchaeotaarchaeonUBA138",
                                                                                   "Methanomassiliicoccussp.UBA382",
                                                                                   "MethanomassiliicoccalesarchaeonUBA147",
                                                                                   "ThermoplasmatalesarchaeonUBA263",
                                                                                   "ThermoplasmatalesarchaeonUBA572",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA407",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA408",
                                                                                   "ThermoplasmatalesarchaeonUBA576",
                                                                                   "ThermoplasmatalesarchaeonUBA574",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA472",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA309",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA354",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA483",
                                                                                   "ThermoplasmatalesarchaeonUBA580",
                                                                                   "ThermoplasmatalesarchaeonUBA579",
                                                                                   "EuryarchaeotaarchaeonUBA169",
                                                                                   "MethanomassiliicoccalesarchaeonUBA149",
                                                                                   "Methanomassiliicoccussp.UBA393",
                                                                                   "Methanomassiliicoccussp.UBA386",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA421",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA317",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA271",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA404",
                                                                                   "ThermoplasmatalesarchaeonUBA513",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA343",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA400",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA399",
                                                                                   "ThermoplasmatalesarchaeonUBA509",
                                                                                   "ThermoplasmatalesarchaeonUBA508",
                                                                                   "ThermoplasmatalesarchaeonUBA568",
                                                                                   "MethanomassiliicoccalesarchaeonUBA280",
                                                                                   "ThermoplasmatalesarchaeonUBA270",
                                                                                   "ThermoplasmatalesarchaeonUBA517",
                                                                                   "ThermoplasmatalesarchaeonUBA516",
                                                                                   "ThermoplasmatalesarchaeonUBA504",
                                                                                   "ThermoplasmatalesarchaeonUBA507",
                                                                                   "ThermoplasmatalesarchaeonUBA522",
                                                                                   "ThermoplasmatalesarchaeonUBA521",
                                                                                   "EuryarchaeotaarchaeonUBA491",
                                                                                   "Methanomassiliicoccussp.UBA321",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA366",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA296",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA415",
                                                                                   "ThermoplasmatalesarchaeonUBA582",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA358",
                                                                                   "ThermoplasmatalesarchaeonUBA512",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA414",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA381",
                                                                                   "ThermoplasmatalesarchaeonUBA447",
                                                                                   "ThermoplasmatalesarchaeonUBA616",
                                                                                   "Methanomassiliicoccussp.UBA335",
                                                                                   "CandidatusMethanomethylophilussp.UBA78",
                                                                                   "Methanomassiliicoccussp.UBA315",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA75",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA481",
                                                                                   "ThermoplasmatalesarchaeonUBA266",
                                                                                   "ThermoplasmataarchaeonUBA61",
                                                                                   "ThermoplasmatalesarchaeonUBA262",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA71",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA537",
                                                                                   "Methanomassiliicoccussp.UBA345",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA306",
                                                                                   "ThermoplasmatalesarchaeonUBA613",
                                                                                   "ThermoplasmatalesarchaeonUBA505",
                                                                                   "ThermoplasmatalesarchaeonUBA611",
                                                                                   "ThermoplasmatalesarchaeonUBA612",
                                                                                   "FerroplasmaceaearchaeonUBA567",
                                                                                   "ThermoplasmatalesarchaeonUBA566",
                                                                                   "Methanomassiliicoccussp.UBA429",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA422",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA371",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA370",
                                                                                   "ThermoplasmatalesarchaeonUBA268",
                                                                                   "ThermoplasmatalesarchaeonUBA269",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA298",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA113",
                                                                                   "ThermoplasmatalesarchaeonUBA564",
                                                                                   "ThermoplasmatalesarchaeonUBA565",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA367",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA314",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA480",
                                                                                   "EuryarchaeotaarchaeonUBA136",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA333",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA329",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA328",
                                                                                   "ThermoplasmatalesarchaeonUBA571",
                                                                                   "ThermoplasmatalesarchaeonUBA578",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA248",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA427",
                                                                                   "ThermoplasmatalesarchaeonUBA617",
                                                                                   "ThermoplasmatalesarchaeonUBA445",
                                                                                   "ThermoplasmatalesarchaeonUBA577",
                                                                                   "ThermoplasmatalesarchaeonUBA444",
                                                                                   "Methanomassiliicoccussp.UBA6",
                                                                                   "Methanomassiliicoccussp.UBA364",
                                                                                   "Methanomassiliicoccussp.UBA360",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA48",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA344",
                                                                                   "EuryarchaeotaarchaeonUBA488",
                                                                                   "EuryarchaeotaarchaeonUBA440",
                                                                                   "EuryarchaeotaarchaeonUBA102",
                                                                                   "ThermoplasmatalesarchaeonUBA570",
                                                                                   "ThermoplasmatalesarchaeonUBA520",
                                                                                   "ThermoplasmatalesarchaeonUBA518",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA72",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA319",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA359",
                                                                                   "MethanomassiliicoccaceaearchaeonUBA308",
                                                                                   "Thermoplasmataarchaeon",
                                                                                   "ThermoplasmataarchaeonHGW-Thermoplasmata-1",
                                                                                   "ThermoplasmataarchaeonHGW-Thermoplasmata-2",
                                                                                   "ThermoplasmataarchaeonM8B2D",
                                                                                   "ThermoplasmataarchaeonM9B1D",
                                                                                   "ThermoplasmataarchaeonM11B2D",
                                                                                   "ThermoplasmataarchaeonM9B2D",
                                                                                   "ThermoplasmatalesarchaeonSW_10_69_26",
                                                                                   "Methanomassiliicoccaceaearchaeon",
                                                                                   "Thermoplasmasp.Kam2015",
                                                                                   "Methanomassiliicoccalesarchaeon",
                                                                                   "CandidatusMethanomethylophilusalvus",
                                                                                   "Methanomassiliicoccussp.",
                                                                                   "CandidatusMethanarcanumhacksteinii",
                                                                                   "MethanomassiliicoccalesarchaeonMx-03",
                                                                                   "CandidatusMethanomassiliicoccusintestinalis",
                                                                                   "MethanomassiliicoccalesarchaeonMx-06",
                                                                                   "CandidatusMethanomethylophilaceaearchaeon",
                                                                                   "Thermoplasmasp.",
                                                                                   "CandidatusMethanoplasmasp.",
                                                                                   "MethanomassiliicoccaceaearchaeonDOK",
                                                                                   "Thermoplasmatalesarchaeon",
                                                                                   "MarineGroupIIIeuryarchaeote",
                                                                                   "CandidatusSysuiplasmajiujiangense",
                                                                                   "CandidatusSysuiplasmasuperficiale",
                                                                                   "CandidatusSysuiplasmaacidicola",
                                                                                   "unculturedCandidatusMethanomethylophilussp.",
                                                                                   "Methanomassiliicoccusluminyensis",
                                                                                   "unculturedmarinegroupIIIeuryarchaeote",
                                                                                   "unculturedMethanomassiliicoccaceaebacterium",
                                                                                   "unculturedMethanomassiliicoccussp.",
                                                                                   "unculturedMethanomassiliicoccalesarchaeon",
                                                                                   "marinemetagenome",
                                                                                   "sedimentmetagenome",
                                                                                   "hydrothermalventmetagenome",
                                                                                   "microbialmatmetagenome",
                                                                                   "marinesedimentmetagenome",
                                                                                   "hydrocarbonmetagenome",
                                                                                   "seawatermetagenome",
                                                                                   "alkalisedimentmetagenome",
                                                                                   "marineplanktonmetagenome",
                                                                                   "estuarymetagenome",
                                                                                   "subsurfacemetagenome",
                                                                                   "aquaticmetagenome",
                                                                                   "metagenome",
                                                                                   "marinemicroorganismAG-341-M17",
                                                                                   "marinemicroorganismAG-341-P21",
                                                                                   "marinemicroorganismAG-341-O18",
                                                                                   "marinemicroorganismAG-341-J21",
                                                                                   "marinemicroorganismAG-331-K15",
                                                                                   "marinemicroorganismAG-331-C09",
                                                                                   "coldseepmetagenome",
                                                                                   "enrichmentculture",
                                                                                   "unculturedprokaryote"))

# write table for further downloads
write.table(subset_assemblies, file="subset_assemblies_scientific_name.txt", sep="\t", row.names=FALSE)
